openapi: 3.0.3
info:
  title: vos360 media lite public API
  description: |-
    This is the public API to configure, operate and monitor the VOS360-Lite.  The API is organized in categories.  They are:

    - Live
    - Notification
    - origin-engine
    
  termsOfService: https://www.vos360medialite.video/terms/
  contact:
    email: vos360medialite_api@vos360.video
  license:
    name: vos360medialite
    url: https://www.vos360medialite.video/licenses/LICENSE-1.0.html
  version: 1.0.0
servers: 
  - url: https://www.vos360medialite.video/api
tags:
  - name: live
  - name: notification
  - name: origin-engine
paths:
  /live/v1/events:
    get:
      summary: List all the live Events
      tags:
        - live
      description: list all the live Events
      operationId: listLiveEvents
      security:
      - vos360lite_auth:
          - write:live
          - read:live
    post:
      summary: Create a live Event
      tags:
        - live
      description: create a live Event
      operationId: createLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/events/{id}:
    get:
      summary: Show a live Event details
      tags:
        - live
      description: list a live Event
      operationId: listLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Update a live Event
      tags:
        - live
      description: update a live Event
      operationId: updateLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    delete:
      summary: Delete a live Event
      tags:
        - live
      description: delete a live Event
      operationId: deleteLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live   
  /live/v1/events/{id}/offline:
    put:
      summary: Action to offline the live event with id
      tags:
        - live
      description: offline the live event
      operationId: offlineLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live      
  /live/v1/events/{id}/preview:
    put:
      summary: Action to preview the live event with id
      tags:
        - live
      description: preview the live event
      operationId: previewLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live 
  /live/v1/events/{id}/goLive:
    put:
      summary: Action to goLive the live event with id
      tags:
        - live
      description: goLive the live event
      operationId: goLiveLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live 
  /live/v1/events/{id}/end:
    put:
      summary: Action to end the live event with id
      tags:
        - live
      description: End the live event
      operationId: endLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live 
  /live/v1/events/{id}/insertSlate:
    put:
      summary: Action to insert Slate image to the live event with id
      tags:
        - live
      description: insert slate to the live event
      operationId: insertSlateLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live 
  /live/v1/events/{id}/removeSlate:
    put:
      summary: Action to remove Slate image to the live event with id
      tags:
        - live
      description: remove slate to the live event
      operationId: removeSlateLiveEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live 
  /notification/v1/settings:
    get:
      summary: Notification webhook setting
      tags:
        - notification
      description: returns the notification settings
      operationId: getNotificationSetting
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Update notification settings
      tags:
        - notification
      description: returns the notification settings
      operationId: updateNotificationSettings
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/settings:
    get:
      summary: Get live event app settings
      tags:
        - live
      description: returns the live settings
      operationId: getLiveSettings
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Update liveEvents settings
      tags:
        - live
      description: returns the liveEvents settings
      operationId: updateLiveEventSettings
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /origin-engine/v1/streamingEndpoint:
    get:
      summary: Get origin streaming endpoint related to streaming units reserved
      tags:
        - origin-engine
      description: returns the streaming capacity reservation
      operationId: getStreamingEndpointReservedUnits
      security:
      - vos360lite_auth:
          - write:live
          - read:live
    put:
      summary: Updates the origin endpoint related to capacity reservation
      tags:
        - origin-engine
      description: Updates the origin endpoint config
      operationId: updateOriginEndpoint
      security:
        - vos360lite_auth:
            - write:medialite
            - read:medialite
  /origin-engine/v1/dynamicPackaging:
    get:
      summary: Get the list of dynamic packaging config
      tags:
        - origin-engine
      description: Dynamic Packaging is Package on the Fly (POTF) of multi-bitrate content to streaming formats.  It is tight to a storage account where mp4 or ismv files are located.  Each dynamic packaging configuration can have an account and packaging format/DRM configured.
      operationId: getDynamicPackagingConfigs
      security:
      - vos360lite_auth:
          - write:medialite
          - read:medialite
    post:
      summary: Create dynamic packaging config
      tags:
        - origin-engine
      description: Dynamic Packaging is Package on the Fly (POTF) of multi-bitrate content to streaming formats.  It is tight to a storage account where mp4 or ismv files are located.  Each dynamic packaging configuration can have an account and packaging format/DRM configured.
      operationId: createDynamicPackagingConfigs
      security:
        - vos360lite_auth:
            - write:medialite
            - read:medialite  
  /origin-engine/v1/dynamicPackaging/{id}:
    get:
      summary: list dynamic packaging details
      tags:
        - origin-engine
      description: list dynamic packaging
      operationId: listDynamicPackaging
      security:
        - vos360lite_auth:
            - write:medialite
            - read:medialite
    put:
      summary: Update Dyanmic Packaging
      tags:
        - origin-engine
      description: update Dynamic Packaging
      operationId: updateDynamicPackaging
      security:
        - vos360lite_auth:
            - write:medialite
            - read:medialite
    delete:
      summary: Delete a Dynamic Packaging
      tags:
        - origin-engine
      description: delete a Dynamic Packaging
      operationId: deleteDynamicPackaging
      security:
        - vos360lite_auth:
            - write:medialite
            - read:medialite
  /origin-engine/v1/dynamicPackaging/{id}/offline:
    put:
      summary: Action to offline the Dynamic Packaging by id
      tags:
        - origin-engine
      description: offline the Dynamic Packaging
      operationId: offlineDynamicPackaging
      security:
        - vos360lite_auth:
            - write:medialite
            - read:medialite    
  /origin-engine/v1/dynamicPackaging/{id}/online:
    put:
      summary: Action to online the Dynamic Packaging by id
      tags:
        - origin-engine
      description: online the Dynamic Packaging
      operationId: onlineDynamicPackaging
      security:
        - vos360lite_auth:
            - write:medialite13
            - read:medialite    
components:
  securitySchemes:
    vos360lite_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://vos360lite.vos360.video/oauth/authorize
          scopes:
            write:liveEvent: modify liveEvents
            read:liveEvent: read your liveEvents
