openapi: 3.0.3
info:
  title: vos360 media lite public API
  description: |-
    This is the public API to configure, operate and monitor the VOS360-Lite.  The API is organized in categories.  They are:

    - LiveEvents
    - Notification
    - origin-engine
    
  termsOfService: https://www.vos360medialite.video/terms/
  contact:
    email: vos360medialite_api@vos360.video
  license:
    name: vos360medialite
    url: https://www.vos360medialite.video/licenses/LICENSE-1.0.html
  version: 1.0.0
servers: 
  - url: https://www.vos360medialite.video/api
tags:
  - name: liveEvents
  - name: notification
  - name: origin-engine

paths:
  /live/v1/channels:
    get:
      summary: List all the live Channels
      tags:
        - liveEvents
      description: list all the live Channels
      operationId: listLiveChannels
      security:
      - vos360lite_auth:
          - write:live
          - read:live
    post:
      summary: Create a live Channel
      tags:
        - liveEvents
      description: create a live Channel
      operationId: createLiveChannel
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/channels/{id}:
    get:
      summary: Find live Channel by ID
      tags:
        - liveEvents
      description: Returns a single live Channel
      operationId: getLiveChannelById
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Updates a live Channel
      tags:
        - liveEvents
      description: Updates a single live Channel
      operationId: updateLiveChannelById
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    delete:
      summary: Deletes a live Channel
      tags:
        - liveEvents
      description: delete a live Channel
      operationId: deleteLiveChannel
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/channels/{id}/playback:
    get:
      summary: Live Channel Playback URLs
      tags:
        - liveEvents
      description: Returns a URL endpoints of a liveChannel
      operationId: getLiveChannelPlaybackUrlById
      security:
      - vos360lite_auth:
          - write:live
          - read:live
  /live/v1/events:
    get:
      summary: List of all events
      tags:
        - liveEvents
      description: list all events
      operationId: listEvents
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    post:
      summary: Create an event
      tags:
        - liveEvents
      description: create an event
      operationId: createEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/events/{id}:
    get:
      summary: Find event by ID
      tags:
        - liveEvents
      description: Returns a single event
      operationId: getEventById
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Updates an event
      tags:
        - liveEvents
      description: Updates a single event
      operationId: updateEventById
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    delete:
      summary: Deletes an event
      tags:
        - liveEvents
      description: delete an event
      operationId: deleteEvent
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/events/{id}/playback:
    get:
      summary: Event Playback URLs
      tags:
        - liveEvents
      description: Returns a URL endpoints of an event
      operationId: getEventPlaybackUrlById
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /notification/v1/settings:
    get:
      summary: Notification webhook setting
      tags:
        - notification
      description: returns the notification settings
      operationId: getNotificationSetting
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Update notification settings
      tags:
        - notification
      description: returns the notification settings
      operationId: updateNotificationSettings
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /live/v1/settings:
    get:
      summary: Get live event app settings
      tags:
        - liveEvents
      description: returns the live settings
      operationId: getLiveSettings
      security:
        - vos360lite_auth:
            - write:live
            - read:live
    put:
      summary: Update liveEvents settings
      tags:
        - liveEvents
      description: returns the liveEvents settings
      operationId: updateLiveEventSettings
      security:
        - vos360lite_auth:
            - write:live
            - read:live
  /origin-engine/v1/streamingEndpoint:
    get:
      summary: Get origin streaming endpoint related to streaming units reserved
      tags:
        - origin-engine
      description: returns the streaming capacity reservation
      operationId: getStreamingEndpointReservedUnits
      security:
      - vos360lite_auth:
          - write:live
          - read:live
    put:
      summary: Updates the origin endpoint related to capacity reservation
      tags:
        - origin-engine
      description: Updates the origin endpoint config
      operationId: updateOriginEndpoint
      security:
        - vos360lite_auth:
            - write:liveEvent
            - read:liveEvent
components:
  securitySchemes:
    vos360lite_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://vos360lite.vos360.video/oauth/authorize
          scopes:
            write:liveEvent: modify liveEvents
            read:liveEvent: read your liveEvents
